apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
type: Opaque
stringData:
  LITELLM_MASTER_KEY: sk-change-me
  DATABASE_URL: postgresql://user:pass@db:5432/litellm
  REDIS_PASSWORD: ""
  AZURE_API_KEY: ""
  AZURE_API_BASE: ""
  AZURE_DEPLOYMENT_NAME: ""
