services:

  app:
    build: .
    env_file: .env
    command: > 
      sh -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: