model_list:
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: ${OPENAI_API_KEY}
      rpm: 60
      tpm: 100000
  - model_name: claude-4-sonnet-latest
    litellm_params:
      model: anthropic/claude-4-sonnet-latest
      api_key: ${ANTHROPIC_API_KEY}
      rpm: 60
      tpm: 100000

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  database_url: ${DATABASE_URL}
  database_connection_pool_limit: 10
  proxy_batch_write_at: 60

router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: redis
  redis_port: 6379
  redis_password: ${REDIS_PASSWORD}

features:
  separate_health_app: true
  pre_call_health_checks: true
